artist:
  name: Cowboy General
  tagline: Fictional Western Rap band headquartered in Atlanta, GA
  # seo_title:
  # seo_description:
  # contact_twitter_username:
  # contact_phone: 
  # contact_email: 

social:
  - name: Facebook
    url: https://www.facebook.com/CareyHoodPhotos/
  - name: Instagram
    url: https://www.instagram.com/careyhood/
  - name: Twitter
    url: https://twitter.com
  - name: Youtube
    url: https://youtube.com
  - name: Spotify
    url: https://spotify.com

site_language: en
